.TH imapget 1 "Feb 2015" "imapget version 1.0"
.SH NAME
imapget [-vhf] -c config
.SH DESCRIPTION
imapget is an IMAP mail retrival tool.  
.SH ARGUMENTS
-v for verbose, -h for help, -f to run in the foreground.  -c is
mandatory and must specify the config file.
.SH NOTES
The author was too tired of nroff to write much for this manpage.  
See imapget.conf(5) for an example configuration file.
.SH "SEE ALSO"
.BR imapget.conf(5)
.SH AUTHOR
.B imapget
was written by Steven Young <sdyoung@miranda.org>.
